:concurrency: 5
:queues:
  - default
  - news_fetch
:timeout: 30
:redis:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
:redis:
  url: <%= ENV['REDIS_URL'] || 'redis://localhost:6379/0' %>
